# This is profile config

server_addr = ":8031"             #server地址
read_timeout = 10                 #server读超时时间
write_timeout = 10                #server写超时时间
max_header_bytes = 20             #最大header头长度
allow_host = [                    #白名单ip
    "127.0.0.1",
    "192.168.1.100",
    "192.168.1.101",
    "192.168.1.102",
    "192.168.1.103",
    "192.168.1.104",
    "192.168.1.105",
    "192.168.1.106"
]